### ISSUE TITLE
Bottom overflow by "X' pixel on iphone 5/5S device

### ISSUE THREAD

**Issue by adoratour** [pedromassango/bottom_navy_bar#59] opened 2020-06-02 13:01 UTC
Hi,
i am doing muti-screen and i got this issue, could you please fix this

**Comment by ventr1x** [comment] 2020-07-04 15:57
It's not a bug but simply a massive oversight and bad calculation. This happens on MANY devices, especially Android.
There is no way to control the width of BottomNavyBarItem, it being completely calculated out of our control.
This makes this plugin entirely useless and I'm sorry for anyone using this in production and not realising this fun result for many many of their users.

**Comment by pedromassango** [comment] 2020-07-18 15:23
Hi @adoratour , @ventr1x 

Could you please provide steps to reproduce this issue if you still having it? Thanks

**Comment by pedromassango** [comment] 2020-11-25 16:37
Whithout more information I am going to close this issue. For anyone facing this same issue please open a new one and link to this one as well.

**Closed by pedromassango** 2020-11-25 16:37 UTC
Labels: bug, waiting customer response
