### ISSUE TITLE
Scroll Position

### ISSUE THREAD

**Issue by Renatinaveen** [pedromassango/bottom_navy_bar#30] opened 2019-10-30 12:02 UTC
The scroll position of one screen is getting reset after coming back from another.
ex: In HomePage i scrolled  to bottom and went to another page then went to home page the scroll position is top. Any solution? 

If i want to add newsfeed i need to maintain the scroll position it's necessary. Look into this. 
Thanks.

**Comment by pedromassango** [comment] 2019-10-30 18:45
Hi @Renatinaveen thanks for this issue. Is it possible to show me a visual issue? it will help to fix this issue

**Comment by Renatinaveen** [comment] 2019-10-31 01:20
![Screenshot_20191031-064651](https://user-images.githubusercontent.com/23468654/67910837-4a3c7900-fbaa-11e9-87b9-a2ebb8b1962c.jpg)
![Screenshot_20191031-064638](https://user-images.githubusercontent.com/23468654/67910839-4a3c7900-fbaa-11e9-9f6a-c1c48a5a6114.jpg)


In 1st screen shot it's starting of the page and the second screenshot is the scrolled one. If i change the tab and come back to home it's going back to the initial scroll position which is top. What i need is to be on the scroll position untill you scroll back to top. I hope you get the idea now and can help. Thanks

**Comment by omishah** [comment] 2019-12-13 08:58
> The scroll position of one screen is getting reset after coming back from another.
> ex: In HomePage i scrolled to bottom and went to another page then went to home page the scroll position is top. Any solution?
> 
> If i want to add newsfeed i need to maintain the scroll position it's necessary. Look into this.
> Thanks.

The issue is not due to this package, it's by flutter framework.
If you want to keep the scroll state, implement Stack with Offstage.

Check below for a complete example:

```
import 'package:bottom_navy_bar/bottom_navy_bar.dart';
import 'package:flutter/material.dart';

class Demo extends StatefulWidget {

  @override
  _DemoState createState() => _DemoState();
}

class _DemoState extends State<Demo> {

  int _currentIndex = 0;

  Stack _bodyWidgets() {
    return Stack( children: <Widget>[
      Offstage(
          offstage: _currentIndex != 0,
          child: TickerMode(enabled: _currentIndex == 0, child: _screen1Body())),
      Offstage(
        offstage: _currentIndex != 1,
        child: TickerMode(
          enabled: _currentIndex == 1,
          child: Text(("Screen 2"),
        ),
      )),
      Offstage(
        offstage: _currentIndex != 2,
        child: TickerMode(
          enabled: _currentIndex == 2,
          child: Text("Screen 3")),
        ),
    ]);
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
        appBar: AppBar(
          title: Text("DEMO"),
        ),
        body: _bodyWidgets(),
        bottomNavigationBar: BottomNavyBar(
            selectedIndex: _currentIndex,
            onItemSelected: (index) => _onTabTapped(index),
            showElevation: true,
            items: [
              BottomNavyBarItem(
                  icon: Icon(Icons.home),
                  title: Text('Screen1')),
              BottomNavyBarItem(
                  icon: Icon(Icons.photo),
                  title: Text('Screen2'),
              ),
              BottomNavyBarItem(
                  icon: Icon(Icons.notifications),
                  title: Text('Screen3'),
                 ),
             
            ]));
  }

  void _onTabTapped(int index) {
    setState(() {
      _currentIndex = index;
    });
  }

  _screen1Body() {
    return ListView.builder(
      itemCount: 100,
      itemBuilder: (context, i) {
        return Padding(padding: EdgeInsets.all(5), child: Text(i.toString()));
      },
    );
  }
}

 
```

**Comment by djaygit** [comment] 2020-02-24 13:57
@omishah what if we try with page controller?

**Comment by pedromassango** [comment] 2020-02-25 09:49
Since this seems to not be a package error, I'm closing it for now.

**Closed by pedromassango** 2020-02-25 09:49 UTC
