### ISSUE TITLE
Too laggy

### ISSUE THREAD

**Issue by mhbdev** [pedromassango/bottom_navy_bar#49] opened 2020-02-25 23:20 UTC
This is so Laggy!!!
Is there any way to solve this problem?

**Comment by pedromassango** [comment] 2020-02-26 08:52
Thanks for your feedback. Can you explain what is going wrong?

**Comment by djaygit** [comment] 2020-02-28 10:07
yes its laggy for me too, i thought flutter is slow lol (new to flutter)

https://im7.ezgif.com/tmp/ezgif-7-a146cff81d9a.gif

**Comment by pedromassango** [comment] 2020-02-28 16:39
Can you show me your implementation?

**Comment by djaygit** [comment] 2020-02-29 14:28
> class _MainTabScreenState extends State<MainTabScreen> {

  int _currentIndex = 0;
  PageController _pageController;

  @override
  void initState() {
    super.initState();
    _pageController = PageController();
  }

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SizedBox.expand(
        child: PageView(
          controller: _pageController,
          onPageChanged: (index) {
            setState(() => _currentIndex = index);
          },
          children: <Widget>[
            Profile(),
            SwipeFeedPage(),
            ChatList(),
          ],
        ),
      ),
      bottomNavigationBar: BottomNavyBar(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        backgroundColor: Colors.white,
        selectedIndex: _currentIndex,
        onItemSelected: (index) {
          setState(() => _currentIndex = index);
          _pageController.jumpToPage(index);
        },
        items: <BottomNavyBarItem>[
          BottomNavyBarItem(
            title: Text('Profile'),
            icon: Icon(Icons.supervised_user_circle),
            activeColor: Colors.red,
            textAlign: TextAlign.center,
          ),
          BottomNavyBarItem(
            title: Text('MatchBox'),
            icon: Icon(Icons.apps),
            textAlign: TextAlign.center,
          ),
          BottomNavyBarItem(
            title: Text('Message'),
            icon: Icon(Icons.chat_bubble),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}

**Comment by djaygit** [comment] 2020-03-11 07:41
what do you think?

**Comment by pedromassango** [comment] 2020-03-11 08:47
Sorry I tested your code but didn't come to give you a feedback. Your code is working fine here. Have you any other piece of code that can cause this behaviour?

**Comment by aresares** [comment] 2020-03-14 20:14
> what do you think?

it's lag also to me but only when the widget that is going to open is to complex, heavy

**Comment by pedromassango** [comment] 2020-03-15 09:39
> it's lag also to me but only when the widget that is going to open is to complex, heavy

What type of heavy complexity/operations are you doing there?

Maybe the problem is not related to this package

**Comment by aresares** [comment] 2020-03-15 19:46
> > it's lag also to me but only when the widget that is going to open is to complex, heavy
> 
> What type of heavy complexity/operations are you doing there?
> 
> Maybe the problem is not related to this package

I don't think it's related to your library. It lags to me when it's going to open a widget with a lot of lines (complex, many other widgetsh inside). With light layouts it's not lagging

**Comment by mhbdev** [comment] 2020-03-15 20:00
Hey guys try running your apps in profile mode using --profile argument! That's not laggy that much in release mode or profile mode!!!

**Comment by pedromassango** [comment] 2020-03-16 09:43
> > > it's lag also to me but only when the widget that is going to open is to complex, heavy
> > 
> > 
> > What type of heavy complexity/operations are you doing there?
> > Maybe the problem is not related to this package
> 
> I don't think it's related to your library. It lags to me when it's going to open a widget with a lot of lines (complex, many other widgetsh inside). With light layouts it's not lagging

Good. So I will close this for now, But the chat can continue here...

**Closed by pedromassango** 2020-03-16 09:43 UTC
Labels: bug, waiting customer feedback
